### ISSUE TITLE
api-gw 연동 기능 추가

### ISSUE THREAD

**Issue by vanilet** [IoTKETI/citydatahub_cloud_management_module#2]
API-GW가 cloud management module의 각 하위 모듈과 서로 REST API 통신이 가능하도록 기능 추가 필요.
Open API 문서: [cloud management module open-api 문서](http://citydatahub.kr/openapi/innogrid)

시나리오 
1. 클라이언트가 Citydatahub의 open-api 문서를 참고하여 api-gw로 요청을 보냄
2. API-GW는 open-api 문서대로 요청을 해당 cloud management module의 하위 모듈로 전달함
3. cloud management module의 하위 모듈은 api-gw가 전송한 요청을 처리하고 결과를 반환함
4. api-gw는 cloud management module의 하위 모듈의 결과를 클라이언트로 전달함

**Comment by kimsh1006** [comment]
cloud management module의 내부 통신은 eureka를 사용하여 서로 연동이 되어있어 api 통신이 가능함
하지만 API-GW와 외부 통신의 경우 사용자가 연동하고자 하는 API-GW의 정보를 가지고 client단에서 구현해야하는 부분
