### ISSUE TITLE
문서화 개선

### ISSUE THREAD

**Issue by vanilet** [IoTKETI/citydatahub_cloud_management_module#3]
현재 Cloud Management Module은 12개 하위 모듈로 구성되어 있음
각 모듈이 어떤 기능을 하는지 문서화가 되어있지 않아 프로젝트 구성 파악이 힘든 문제가 있음

개선이 필요한 사항은 아래와 같음
* 각 모듈이 어떤 기능을 하는지 설명 추가
* 각 모듈 간 연계가 어떻게 되는지 설명 추가
* cli에서 각 모듈을 어떻게 빌드하고 실행하는지 설명 추가
* 클라우드 관리 모듈을 사용하려면 어떤 순서로 하위 모듈을 실행해야 하는지 설명 추가
* 사용자가 클라우드 관리 모듈을 어떻게 사용할 수 있는지 설명 추가

추가적으로 클라우드 관리 모듈을 개발자와 운영자가 사용을 할 것인데, 개발자와 운영자가 어떻게 사용해야 하는지 설명이 부족함
이를 개선하기 위해 참고할만한 메뉴얼은 아래와 같음
* [data ingest 모듈 메뉴얼](http://docs.citydatahub.kr/docs/ingest/intro)
* [security 모듈 메뉴얼](http://docs.citydatahub.kr/docs/security/intro)
* [data core 모듈 메뉴얼](http://docs.citydatahub.kr/docs/datacore/intro)

**Comment by kimsh1006** [comment]
README.md 업데이트
